// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from muse_elements_algorithm_settings.djinni

#import <Foundation/Foundation.h>

/**
 * The following is an interface that lets you get and set which
 * algorithm version to use.
 */
typedef NS_ENUM(NSInteger, IXNMuseElementsVersion)
{
    IXNMuseElementsVersionV20,
    IXNMuseElementsVersionV30,
    IXNMuseElementsVersionR10,
    IXNMuseElementsVersionV40,
    IXNMuseElementsVersionV50,
};
