// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from packets.djinni

#import <Foundation/Foundation.h>

/**
 * \if IOS_ONLY
 * \file
 * \endif
 * Represents the data mapping in an EEG packet.
 * Enum values correspond to head locations.
 *
 * Raw EEG values are given in microvolts. EEG derived values may have different units
 * as defined in \classlink{MuseDataPacketType}.
 *
 * \sa \enumlink{MuseDataPacketType,EEG,IXNMuseDataPacketTypeEeg}
 * \sa \functionlink{MuseDataPacket,getEegChannelValue,get_eeg_channel_value}
 */
typedef NS_ENUM(NSInteger, IXNEeg)
{
    /** Left ear */
    IXNEegEEG1,
    /** Left forehead */
    IXNEegEEG2,
    /** Right forehead */
    IXNEegEEG3,
    /** Right ear */
    IXNEegEEG4,
    /** Left auxiliary (maps to AUX1 on \muse2025). */
    IXNEegAUXLEFT,
    /** Right auxiliary (maps to AUX2 on \muse2025). */
    IXNEegAUXRIGHT,
    /** Auxiliary input 1 on \muse2025. */
    IXNEegAUX1,
    /** Auxiliary input 2 on \muse2025. */
    IXNEegAUX2,
    /** Auxiliary input 3 on \muse2025 */
    IXNEegAUX3,
    /** Auxiliary input 4 on \muse2025 */
    IXNEegAUX4,
};
