// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from muse_elements_algorithm_settings.djinni

#import "Muse/internal/IXNMuseElementsVersion.h"
#import <Foundation/Foundation.h>
@class IXNMuseElementsAlgorithmSettings;


@interface IXNMuseElementsAlgorithmSettings : NSObject

+ (nullable IXNMuseElementsAlgorithmSettings *)getInstance;

- (IXNMuseElementsVersion)getElementsVersion;

- (void)setElementsVersion:(IXNMuseElementsVersion)version;

- (void)setEnableMultipleMuseElements:(BOOL)enable;

- (BOOL)getEnableMultipleMuseElements;

@end
