// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from packets.djinni

#import <Foundation/Foundation.h>

/**
 * \if IOS_ONLY
 * \file
 * \endif
 * Represents the data mapping in a Battery packet.
 * \sa \enumlink{MuseDataPacketType,BATTERY,IXNMuseDataPacketTypeBattery}
 * \sa \functionlink{MuseDataPacket,getBatteryValue,get_battery_value}
 */
typedef NS_ENUM(NSInteger, IXNBattery)
{
    /** Charge percentage remaining of battery. */
    IXNBatteryChargePercentageRemaining,
    /** Millivolts of battery from the view of the fuel gauge. */
    IXNBatteryMillivolts,
    /** Temperature in degrees Celsius. */
    IXNBatteryTemperatureCelsius,
    /** Average current in microamps. */
    IXNBatteryAverageCurrent,
    /** Remaining seconds until charge depleted (while discharging). */
    IXNBatteryTimeToEmpty,
    /** Remaining seconds until fully charged (while charging). */
    IXNBatteryTimeToFull,
    /** Full capacity of battery in mAh.   */
    IXNBatteryBatteryCapacity,
    /** Remaining capacity of battery in mAh. */
    IXNBatteryRemainingCapacity,
    /** Percentage battery age calculated from capacity. */
    IXNBatteryBatteryAge,
    /** Total number of charge/discharge cycles. */
    IXNBatteryTotalCycles,
};
