// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from museinfo.djinni

#import <Foundation/Foundation.h>

/**
 * \if IOS_ONLY
 * \file
 * \endif
 * The model identifier of the headbands. The model is laser printed on the
 *  inside of the left pod of the headband as either "MU-01", "MU-02", "MU-03" or "MU-06".
 * \muse2019 \muse2021 and \muse2025 models are marked on the underside as "MS-01", "MS-02" or "MS-03".
 */
typedef NS_ENUM(NSInteger, IXNMuseModel)
{
    /** First model of Muse, Muse 2014 */
    IXNMuseModelMu01,
    /** Muse 2016 with Bluetooth Low Energy support. */
    IXNMuseModelMu02,
    /** Muse2 2018 adding PPG sensor, Accelerometer and Gyroscope. */
    IXNMuseModelMu03,
    /** MuseS 2019 softband (MS-01). */
    IXNMuseModelMu04,
    /** MuseS 2021 softband refresh (MS-02). */
    IXNMuseModelMu05,
    /** Muse2 2024 with USB-C connector. */
    IXNMuseModelMu06,
    /** MuseS 2025 softband with USB-C, Bluetooth 5.3, improved EEG and Optics (MS-03). */
    IXNMuseModelMs03,
};
