// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from packets.djinni

#import <Foundation/Foundation.h>

/**
 * \if IOS_ONLY
 * \file
 * \endif
 * Represents the data mapping in an Optics packet.
 *
 * Functional near-infrared spectroscopy (fNIRS) is a non-invasive imaging technique that measures brain
 * activity by detecting changes in blood oxygenation.
 *
 * The light absorbtion of the blood varies by wavelength. The 750nm wavelength is sensitive to deoxygenated
 * hemoglobin (HbR), while the 850nm wavelength is sensitive to oxygenated hemoglobin (HbO). By analyzing the
 * absorption of these wavelengths, we can determine changes in blood oxygenation levels.
 *
 * For more information on fNIRS, see the following Wikipedia article:
 * <br/>
 * https://en.wikipedia.org/wiki/Functional_near-infrared_spectroscopy
 *
 * The Optics data is also used to measure PPG.
 *
 * Optics data values are given in microamps (uA).
 *
 * \sa \enumlink{MuseDataPacketType,OPTICS,IXNMuseDataPacketTypeOptics}
 * \sa \functionlink{MuseDataPacket,getOpticsChannelValue,get_optics_channel_value}
 */
typedef NS_ENUM(NSInteger, IXNOptics)
{
    /** 730nm left outer (8 and 16 channel modes) or 730nm left inner (4 channel mode) */
    IXNOpticsOPTICS1,
    /** 730nm right outer (8 and 16 channel modes) or 730nm right inner (4 channel mode) */
    IXNOpticsOPTICS2,
    /** 850nm left outer (8 and 16 channel modes) or 850nm left inner (4 channel mode) */
    IXNOpticsOPTICS3,
    /** 850nm right outer (8 and 16 channel modes) or 850nm right inner (4 channel mode) */
    IXNOpticsOPTICS4,
    /** 730nm left inner (8 and 16 channel modes) */
    IXNOpticsOPTICS5,
    /** 730nm right inner (8 and 16 channel modes) */
    IXNOpticsOPTICS6,
    /** 850nm left inner (8 and 16 channel modes) */
    IXNOpticsOPTICS7,
    /** 850nm right inner (8 and 16 channel modes) */
    IXNOpticsOPTICS8,
    /** Red left outer (16 channel mode)    */
    IXNOpticsOPTICS9,
    /** Red right outer (16 channel mode) */
    IXNOpticsOPTICS10,
    /** Ambient left outer (16 channel mode) */
    IXNOpticsOPTICS11,
    /** Ambient right outer (16 channel mode) */
    IXNOpticsOPTICS12,
    /** Red left inner (16 channel mode) */
    IXNOpticsOPTICS13,
    /** Red right inner (16 channel mode) */
    IXNOpticsOPTICS14,
    /** Ambient left inner (16 channel mode) */
    IXNOpticsOPTICS15,
    /** Ambient right inner (16 channel mode) */
    IXNOpticsOPTICS16,
};
